apiVersion: v1
kind: PersistentVolume
metadata:
  name: credentials
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    type: local
    intent: credentials
spec:
  capacity:
    storage: 10Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/berkeley-scheduler/server/.credentials"
