apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: credentials-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      intent: credentials
