apiVersion: v1
kind: Pod
metadata:
  name: berkeley-scheduler
spec:
  restartPolicy: Never
  containers:
  - name: update
    image: "berkeleyscheduler/update"
    imagePullPolicy: Always
    volumeMounts:
    - name: enrollment-data
      mountPath: /berkeley-scheduler
#    - name: credentials
#      mountPath: /berkeley-scheduler/server/.credentials
  volumes:
  - name: enrollment-data
    gcePersistentDisk:
      pdName: enrollment-data-pd
      fsType: ext4
#  - name: credentials
#    persistentVolumeClaim:
#      claimName: credentials-claim
