apiVersion: v1
kind: Pod
metadata:
  name: user-accounts
  annotations:
    component: user-accounts
spec:
  restartPolicy: Never
  containers:
  - name: mongo-node
    image: mongo
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongo-persistent-storage
      mountPath: /data/db
  - name: user-accounts-server
    image: berkeleyscheduler/user-accounts
    imagePullPolicy: Always
  volumes:
  - name: mongo-persistent-storage
    gcePersistentDisk:
      pdName: mongodb-pd
      fsType: ext4
