apiVersion: v1
kind: Service
metadata:
  name: user-accounts-service
spec:
  selectors:
    component: user-accounts
  ports:
  - name: https
    protocol: TCP
    port: 443
  externalIPs:
  - "130.211.34.169"
